// @ts-check
/// <reference path="./index.d.ts" />

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { packAsync } = require('free-tex-packer-core');

//============================================================================================
const IMAGES = [
	"./test/bkgard.png",
	"./test/bkblue.png",
	"./test/bkfall.png",
];
const TEXTURE_NAME = "test_atlas";

const CONFIG = {
  outputFolder: './output/',                      //Godot resource file output path
  atlasData: '',                                  //Here is temporary data, and no need set string
  atlasImagePath: 'res://assets/textures/',       //This is the godot resource path, copy or move output files to this path after finished.
  
  // UID : 'random' | 'hash' | 'none'
  uidStrategy: 'hash',
  
  useAtlasUid: true
};
//============================================================================================

const image_data = IMAGES.map(p => {
	return {
		path: /** @type {string} */ (p.split('/').pop()),
		contents: /** @type {Buffer<ArrayBufferLike>} */ (fs.readFileSync(p)),
	};
});

const options = /** @type {import('free-tex-packer-core').TexturePackerOptions} */ ({
	textureName: TEXTURE_NAME,
	exporter: "JsonHash",   //Temporary export json data
	padding: 2,
	allowRotation: false,
	allowTrim: true,
	removeFileExtension: true,
});

async function packAndExport() {
	const outDir = CONFIG.outputFolder;
	fs.mkdirSync(outDir, { recursive: true });

	try {
		const files = await packAsync(image_data, options);

		// files >>>>>>>>>> [{ name: 'xxx.png', buffer: <Buffer> }, { name: 'xxx.json', buffer: <Buffer> }]
		for (const file of files) {
			let filePath = path.join(outDir, file.name);
			fs.writeFileSync(filePath, file.buffer);

      filePath = filePath.replaceAll("\\", "/");
      const extname = path.extname(filePath);
      if (extname === ".json") {
        CONFIG.atlasData = filePath;
      }
      else {
        CONFIG.atlasImagePath += filePath.split('/').pop();
      }

			console.log(`✅ Export success: ${filePath} (${(file.buffer.length / 1024).toFixed(2)} KB)`);
		}
	} catch (err) {
    const typedErr = /** @type {Error} */ (err);
		console.error('❌ Export fail:', typedErr.message);
	}
}

/**
 * Generate Godot 4 compatible UID string
 * @param {string} seed - Seed string used for hashing
 * @returns Format: `uid://xxxxxxxxxxx` (11-character base64-like string)
 */
function generateGodotUID(seed) {
  const hash = crypto.createHash('md5').update(seed + Math.random()).digest('hex');
  const num = BigInt('0x' + hash.substring(0, 16));
  
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-';
  let uid = '';
  let val = num % BigInt(64 ** 11);
  for (let i = 0; i < 11; i++) {
    uid = chars[Number(val % 64n)] + uid;
    val = val / 64n;
  }
  return `uid://${uid}`;
}

/**
 * Generate short reference ID for ext_resource
 * @param {number} index Resource index (usually starts from 1)
 * @returns {string} Format: `{index}_{5 random letters}`, e.g., "1_abcde"
 */
function generateExtId(index) {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  let rand = '';
  for (let i = 0; i < 5; i++) rand += chars[Math.floor(Math.random() * chars.length)];
  return `${index}_${rand}`;
}

/**
 * Convert number to Godot .tres format float string
 * @param {number} num Input number
 * @returns {string} String with 5 decimal places, e.g., `72` → `"72.00000"`
 */
function toGodotFloat(num) {
  return Number(num).toFixed(5);
}

/**
 * Convert TexturePacker JSON to Godot 4 AtlasTexture .tres files
 * @param {string} inputJson Input JSON file path (generated by free-tex-packer-core)
 * @param {string} outputDir Target directory for output .tres files
 * @param {string} atlasRelativePath Atlas path in Godot project
 * @returns {void}
 */
function convertToGodot4TRES(inputJson, outputDir, atlasRelativePath) {
  const data = JSON.parse(fs.readFileSync(inputJson, 'utf-8'));
  const frames = data.frames;
  const atlasUID = generateGodotUID(data.meta.image);
  
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
  
  for (const [name, frameData] of Object.entries(frames)) {
    const extId = generateExtId(1); // Single atlas, fixed ID
    
    const { frame, spriteSourceSize, sourceSize, trimmed } = frameData;
    
    // Generate a UID for the AtlasTexture
    const texUID = generateGodotUID(`${data.meta.image}_${name}`);
    
    const region = `Rect2(${toGodotFloat(frame.x)}, ${toGodotFloat(frame.y)}, ${toGodotFloat(frame.w)}, ${toGodotFloat(frame.h)})`;
    
    let marginLine = '';
    if (trimmed) {
      const left = spriteSourceSize.x;
      const top = spriteSourceSize.y;
      const right = sourceSize.w - spriteSourceSize.x - spriteSourceSize.w;
      const bottom = sourceSize.h - spriteSourceSize.y - spriteSourceSize.h;
      marginLine = `margin = Vector4(${toGodotFloat(left)}, ${toGodotFloat(top)}, ${toGodotFloat(right)}, ${toGodotFloat(bottom)})\n`;
    }

    const tresContent = `[gd_resource type="AtlasTexture" format=3 uid="${texUID}"]

[ext_resource type="Texture2D" uid="${atlasUID}" path="${atlasRelativePath}" id="${extId}"]

[resource]
atlas = ExtResource("${extId}")
region = ${region}
${marginLine}filter_clip = true
`;

    const outputPath = path.join(outputDir, `${name}.tres`);
    fs.writeFileSync(outputPath, tresContent, 'utf-8');
    console.log(`✅ Generate: ${outputPath}`);
  }
}

const promise = packAndExport();
promise.then(() => {
	// console.log(CONFIG);
  convertToGodot4TRES(
    CONFIG.atlasData,
    CONFIG.outputFolder,
    CONFIG.atlasImagePath
  );

  //Delete tmp json file
  fs.rmSync(CONFIG.atlasData);
  console.log(`🚀 Completed!`);
});
