/// <reference types="node" />

// ============================================================================
// Utility Function Types
// ============================================================================

/**
 * Generate Godot 4 compatible UID string
 * @param seed - Seed string used for hashing
 * @returns Format: `uid://xxxxxxxxxxx` (11-character base64-like string)
 * 
 * @example
 * generateGodotUID('my_atlas.png') 
 * // => "uid://kx9m2p4n8q1r"
 */
export function generateGodotUID(seed: string): string;

/**
 * Generate short reference ID for ext_resource
 * @param index - Resource index (usually starts from 1)
 * @returns Format: `{index}_{5 random letters}`, e.g., "1_abcde"
 */
export function generateExtId(index: number): string;

/**
 * Convert number to Godot .tres format float string
 * @param num - Input number
 * @returns String with 5 decimal places, e.g., `72` → `"72.00000"`
 */
export function toGodotFloat(num: number): string;

// ============================================================================
// Core Conversion Functions
// ============================================================================

/**
 * Convert TexturePacker JSON to Godot 4 AtlasTexture .tres files
 * 
 * @param inputJson - Input JSON file path (generated by free-tex-packer-core)
 * @param outputDir - Target directory for output .tres files
 * @param atlasRelativePath - Atlas path in Godot project (e.g., 'res://assets/my_atlas.png')
 * 
 * @throws {Error} When JSON parsing fails or file writing errors occur
 * 
 * @example
 * convertToGodot4TRES(
 *   './output/test_atlas.json',
 *   './output/atlas/',
 *   'res://assets/textures/test_atlas.png'
 * );
 */
export function convertToGodot4TRES(
  inputJson: string,
  outputDir: string,
  atlasRelativePath: string
): void;

/**
 * Pack images and export to Godot compatible format (main entry function)
 * 
 * Process:
 * 1. Read images from IMAGES array
 * 2. Call free-tex-packer-core to generate atlas + JSON
 * 3. Automatically call convertToGodot4TRES to generate .tres files
 * 4. Clean up temporary JSON file
 * 
 * @returns Promise<void>, resolves when packing is complete
 * 
 * @example
 * await packAndExport();
 * console.log('✅ All resources ready for import into Godot');
 */
export function packAndExport(): Promise<void>;
